#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Secrets Manager からシークレットを取得して .env.{env} に書き出す
# 実行前提: EC2 に IAM_R_ka_moneynote_01 がアタッチされていること
# 使い方:
#   ./scripts/secrets-fetch.sh env1   # → .env.env1 を生成
#   ./scripts/secrets-fetch.sh env2   # → .env.env2 を生成
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV="${1:-}"
if [[ "$ENV" != "env1" && "$ENV" != "env2" ]]; then
  echo "Usage: $0 env1|env2"
  exit 1
fi

REGION="ap-northeast-1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/.env.${ENV}"

get_secret() {
  aws secretsmanager get-secret-value \
    --region "${REGION}" \
    --secret-id "$1" \
    --query SecretString \
    --output text \
    | python3 -c "import sys,json; print(list(json.load(sys.stdin).values())[0])"
}

echo "Fetching secrets for ${ENV} from AWS Secrets Manager (region: ${REGION})..."

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_REGISTRY=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

if [[ "$ENV" == "env1" ]]; then
  FRONTEND_URL=https://alb-ka-moneynote-01-567525932.ap-northeast-1.elb.amazonaws.com
elif [[ "$ENV" == "env2" ]]; then
  FRONTEND_URL=https://alb-ka-moneynote-02-changeme.ap-northeast-1.elb.amazonaws.com
fi

DB_PASSWORD=$(get_secret "moneynote/${ENV}/db-password")
JWT_SECRET=$(get_secret "moneynote/${ENV}/jwt-secret")
REDIS_PASSWORD=$(get_secret "moneynote/${ENV}/redis-password")
CLAUDE_API_KEY=$(get_secret "moneynote/${ENV}/claude-api-key")
ADMIN_EMAIL=$(get_secret "moneynote/${ENV}/admin-email")

cat > "${OUTPUT_FILE}" <<EOF
# Generated by scripts/secrets-fetch.sh ${ENV} — DO NOT COMMIT

# ── Secrets Manager から取得した機密情報 ─────────────────────
DB_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
REDIS_PASSWORD=${REDIS_PASSWORD}
CLAUDE_API_KEY=${CLAUDE_API_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL}

# ── 固定値（機密情報ではない）────────────────────────────────
ECR_REGISTRY=${ECR_REGISTRY}
DB_HOST=db
DB_PORT=5432
DB_NAME=moneynote
DB_USERNAME=moneynote
REDIS_HOST=redis
REDIS_PORT=6379
FRONTEND_URL=${FRONTEND_URL}
MAIL_HOST=localhost
MAIL_PORT=1025
EOF

chmod 600 "${OUTPUT_FILE}"

echo "Done. Secrets written to ${OUTPUT_FILE}"
echo "FRONTEND_URL=${FRONTEND_URL}"
echo ""
echo "次のステップ:"
echo "  docker-compose -f docker-compose.${ENV}.yml up -d"
