#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Secrets Manager からシークレットを取得して .env.{env} に書き出す
# 実行前提: EC2 に IAM_R_ka_moneynote_01 がアタッチされていること
# 使い方:
#   ./scripts/secrets-fetch.sh env1   # → .env.env1 を生成
#   ./scripts/secrets-fetch.sh env2   # → .env.env2 を生成
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV="${1:-}"
if [[ "$ENV" != "env1" && "$ENV" != "env2" ]]; then
  echo "Usage: $0 env1|env2"
  exit 1
fi

REGION="ap-northeast-1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/.env.${ENV}"

get_secret() {
  aws secretsmanager get-secret-value \
    --region "${REGION}" \
    --secret-id "$1" \
    --query SecretString \
    --output text \
    | python3 -c "import sys,json; print(list(json.load(sys.stdin).values())[0])"
}

echo "Fetching secrets for ${ENV} from AWS Secrets Manager (region: ${REGION})..."

DB_PASSWORD=$(get_secret "moneynote/${ENV}/db-password")
JWT_SECRET=$(get_secret "moneynote/${ENV}/jwt-secret")
REDIS_PASSWORD=$(get_secret "moneynote/${ENV}/redis-password")
CLAUDE_API_KEY=$(get_secret "moneynote/${ENV}/claude-api-key")

cat > "${OUTPUT_FILE}" <<EOF
# Generated by scripts/secrets-fetch.sh ${ENV} — DO NOT COMMIT
DB_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
REDIS_PASSWORD=${REDIS_PASSWORD}
CLAUDE_API_KEY=${CLAUDE_API_KEY}

# TODO: 以下を ALB の DNS 名に変更してから docker-compose を起動すること
# 例: FRONTEND_URL=https://ALB-ka-moneynote-01-xxxxxxxx.ap-northeast-1.elb.amazonaws.com
FRONTEND_URL=https://TODO_SET_ALB_DNS_NAME
EOF

chmod 600 "${OUTPUT_FILE}"

echo "Done. Secrets written to ${OUTPUT_FILE}"
echo ""
echo "次のステップ:"
echo "  1. ${OUTPUT_FILE} を開いて FRONTEND_URL を ALB の DNS 名に更新する"
echo "  2. docker-compose -f docker-compose.${ENV}.yml up -d --build"
